"""init

Revision ID: 1632a5d1910e
Revises: 
Create Date: 2023-07-07 12:30:19.958658

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1632a5d1910e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
