"""add unique User.email

Revision ID: 80e80485a3ad
Revises: 3b0b5cd61575
Create Date: 2023-07-15 12:47:32.821785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e80485a3ad'
down_revision = '3b0b5cd61575'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint('uc_user_email', 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uc_user_email', 'user', type_='unique')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
