"""add UserRole with surrogate key

Revision ID: 88ecd4db692d
Revises: 80e80485a3ad
Create Date: 2023-07-18 12:12:20.725949

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '88ecd4db692d'
down_revision = '80e80485a3ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'userrole',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['role_id'],
            ['role.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_table('usersrole')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'usersrole',
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['role_id'], ['role.id'], name='usersrole_role_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['user.id'], name='usersrole_user_id_fkey'
        ),
        sa.PrimaryKeyConstraint('user_id', 'role_id', name='usersrole_pkey'),
    )
    op.drop_table('userrole')
    # ### end Alembic commands ###
