"""add v2 passwords

Revision ID: f92fe563e835
Revises: 1632a5d1910e
Create Date: 2023-07-07 12:42:36.891352

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f92fe563e835'
down_revision = '1632a5d1910e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'passwdv2',
        sa.Column('created_on', sa.DateTime(), nullable=False),
        sa.Column('updated_on', sa.DateTime(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('passwd', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ['id'],
            ['user.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passwdv2')
    # ### end Alembic commands ###
