DB:
  #DATABASE_URL: 'sqlite:///./data.db'
  DATABASE_URL: 'postgresql+asyncpg://user:pass@localhost:5432/app'
  DEBUG_MOD: False

APP:
  #ROOT_PATH: '/api'
  ROOT_PATH: ''
  LOGGER_MODE: False
  LOG_FILE: 'py_log.log'

SECURITY:
  SECRET_KEY: 'feojwihewhighigh3347486348y8346946fnbccf0f4caa6cf63b88e8d3e7'
  ALGORITHM: 'HS256'
  ACCESS_TOKEN_EXPIRE_MINUTES: 30
