version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - './.pg_data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'